server.port: 9001

spring:
  application:
    name: springbootConfig
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhou_yangzhong/SpringCloud-Properties.git

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 30